### PR TITLE
Back port logging of 2.2.0 in 2.1 branch

### PR DESCRIPTION
**Pull request by H--o-l**

### CODE REVIEW

**Comment by adrienverge** [comment]
Hey @H--o-l, is it intended to be merged, or just for reference?

**Comment by H--o-l** [comment]
Hey!
His target is a new branch named `branch_2.1`, so it can be merged without consequences on master. Thus it's mostly to show you how I have done it.

(I think a coucharchive 2.1.7 could be made out of it, but it's not necessary).

Idea is to have all the logging capacity that there is in 2.2.0, but with the same algorithm, thus the same performance, as the 2.1.6 version.

**Comment by adrienverge** [comment]
Tests have shown that this PR induces performance issues (very probably linked to the 2 multiprocessing communication problems solved by #28 and #29). So, this PR is unfortunately not "just a backport of logging": it also brings artefacts. For that reason, I suggest closing to avoid bringing these problems to the 2.1.x line.

**Comment by H--o-l** [comment]
Indeed!

**Pull request closed without merging**
